# 2019-08-20 유재명님

## 교육과정
1. 확률
2. 추정
3. 실험
4. 예측 # 예측해서 그래프 그려보기
5. 잠재
    - 예측/관찰할 수 없는 것
> ex. 고객만족도 설문: 만족했다고 답변하지만 실제 만족했는지 알 수 없음
6. 시간

### 만족도 조사의 신뢰도 확인방법
(실제로는 확인하지 않음)
- 만족도가 높으면 재계약율이 높다
- 결합상품 등 추천시 가입율 올라간다

### 실습) 불확실한 상황에서 의사결정
- 최근에 했던 의사결정을 떠올려 보세요
- 또는 곧 해야할 의사 결정을 생각해보세요
- 무엇이 불확실했나요

## Parameter 변수의 종류
연속형(숫자로 나타낼 수 있는 것) | 범주형(이산형)
---|---
여행에서 돈을 얼마나 쓸지 | 저녁 메뉴(피자/치킨) 
ex. 몇시에 일어날지 | ex. 취미(다육이/구피)
-> 평균 등 계산 | -> 퍼센티지 계산

관찰변수 | 잠재변수
--|--
관찰할 수 있는 변수 | 관찰할 수 없는 변수 
ex. 설문지 답변 | ex. 고객 만족도 

**잠재변수도 통계적으로 다룰 수 있다.**

## 척도
- 명목
- 서열: 순서를 쪼개서 늘어놓는 것
    ##### ex. 주변에 추천하고 싶다 - 다시 살 의향이 있다 - 만족 - 불만족 - 컴플레인
- 등간: 0점이 없음. 
    ##### ex. 온도(온도 수치상 2배는 존재하지만 온도로 측정하려고 하는 열이 2배인 것은 아님.) 
    ##### ex. 시험점수(시험 점수 점수가 2배라고 2배 더 잘한다는 건 아님)
- 비율: 0점이 존재해야 함
비율은 항상 등간

## 대표값
- 최빈값 Mode
- 평균 Mean
- 중간값 Median

In [31]:
import numpy as np

In [20]:
x = [200, 100, 100, 200, 300, 10000]

In [15]:
np.mean(x)

1816.6666666666667

In [16]:
np.median(x)

200.0

In [17]:
from scipy.stats import mode

In [21]:
mode(x)

ModeResult(mode=array([100]), count=array([2]))

In [22]:
np.min(x)

100

In [23]:
np.max(x)

10000

In [24]:
np.var(x)

13398055.555555554

In [25]:
np.std(x)

3660.3354430373665

In [139]:
# 중간값은 데잇걸즈 5 명만 조사해도 대략 알수있음
np.quantile(x, .75) # 3 사분위수(75 %) 지점

34.0

In [29]:
x = [0, 0, 0, 0, 0, 0, 0, 0, 0, 100]

In [33]:
from numpy.random import binomial

# Binomial 이항정리

In [71]:
#help(binomial)

In [35]:
x = binomial(100, .3, 30)

In [36]:
min(x)

24

In [37]:
max(x)

39

In [41]:
binomial(100, .3)

29

In [69]:
profit = 0
prepare = 26

for i in x:
    if i < prepare:
        profit += (prepare - i)*(-10000)
        profit += i * 1000
    else:
        profit += prepare * 1000
print(profit)

736000


In [70]:
binomial(100, .1)

8

In [87]:
보험료 = 100
지급액 = 1000
고객 = 100
사망자 = binomial(고객, .1)
매출 = 고객 * 보험료
지급 = 지급액 * 사망자
손익 = 매출 - 지급

손익

6000

# Geometric 기하분포
나올 때까지 하는 거
> ex. 이탈률이 5 % 인 고객인 가입해서 이탈할 때까지 걸린 기간

In [138]:
# 이탈율이 5 % 일 때 100 명의 고객이 며칠 후 이탈할 확률
from numpy.random import geometric

기간 = geometric(.05, 100)

In [94]:
np.sum(기간 * 0.5 - 10)

-114.5

In [95]:
np.sum(기간 * 1 - 100)

-8229

# Negative Binomial 음이항분포
- 기하분포의 일반화
- 성공률이 p 일 때 n 번 성공할 때까지 시도했을 때 총 시도 횟수
- cf. Geometric 은 1 번 성공할 때까지의 기간만 출력 가능

In [96]:
# 세번 짜증나면 나감

짜증 = 0
기간 = 0

while 짜증 < 3:             # 세번째는 못 참는다
    사건 = binomial(1, .05) # 5 % 의 확률로 사건 발생
    if 사건 == 1:           # 사건이 나면
        짜증 += 1           # 짜증이 증가
    기간 += 1
기간

42

In [97]:
from numpy.random import negative_binomial

# 실습

- 우리 리트리버는 10%의 확률로 짜증이 납니다. 
- 이틀 연속으로 짜증이 나면 화를 냅니다. 
- 리트리버가 화를 낼 때까지 기간을 시뮬레이션 해보세요.

In [ ]:
# 세번 짜증나면 나감

짜증 = 0
기간 = 0

while 짜증 < 3:             # 세번째는 못 참는다
    사건 = binomial(1, .05) # 5 % 의 확률로 사건 발생
    if 사건 == 1:           # 사건이 나면
        짜증 += 1           # 짜증이 증가
    기간 += 1
기간

# 포아송 분포
- 평균적으로 L번 일어나는 일이 X 번 일어날 확률의 분포
- 이항분포에서 n 이 크고 p 가 작으면 포아송 분포와 비슷해진다
#### ex. 1시간에 평균 10명의 고객이 방문한다고 할 때 시간당 방문 고객 수

In [98]:
from numpy.random import poisson

In [100]:
# 평균 30 명이 방문하는 박물관의 50일간 입장객 수 
poisson(30, 50)

array([23, 29, 32, 31, 33, 23, 37, 30, 27, 32, 33, 31, 18, 27, 29, 29, 33,
       25, 31, 41, 40, 30, 30, 40, 31, 38, 37, 33, 24, 31, 22, 30, 34, 32,
       27, 39, 22, 33, 23, 30, 35, 38, 37, 34, 28, 19, 29, 23, 35, 29, 32,
       36, 23, 37, 33, 44, 28, 43, 14, 31, 29, 28, 32, 46, 30, 29, 30, 33,
       28, 28, 29, 44, 27, 36, 33, 27, 21, 31, 30, 32, 32, 35, 25, 34, 18,
       25, 25, 27, 24, 35, 21, 27, 29, 40, 29, 26, 32, 49, 31, 23])

In [101]:
# 최대 100 명 중 방문확률
# 여기서 100 명(n) 이 숫자가 커지면 포아송 분포와 비슷해진다
# n 은 각각의 독립변수, 동전 던지기의 경우 던지는 동전의 갯수
binomial(100, .3, 50)

array([33, 27, 33, 32, 28, 32, 25, 23, 25, 33, 31, 30, 31, 29, 31, 31, 28,
       19, 27, 35, 30, 26, 26, 29, 32, 30, 40, 26, 38, 22, 28, 30, 28, 29,
       21, 35, 28, 25, 26, 32, 25, 33, 31, 20, 20, 22, 32, 29, 24, 33])

# 연속확률분포
- 균등분포 Uniform
- 정규분포
- 지수분포

In [102]:
from numpy.random import uniform

In [137]:
# 최소값(10)과 최대값(20) 사이에서 균등한 확률로 숫자를 하나 뽑는다 ~= binomial
uniform(10, 20)

13.48302723241457

In [118]:
uniform(0, 1)

0.1622771212630305

In [136]:
# 1 에서 10 까지 숫자 중에 *정수*를 하나 뽑는다
int(uniform(1, 10))

3

In [147]:
# 원점을 둘러싼 한 변이 2인 정사각형(+-1, +-1)
# 원점을 둘러싼 대각선이 2인 마름모(+-1, +-1)
# 정사각형 안의 점을 하나 뽑았을 때 마름모 안에 들어갈 확률(1/2)

x = uniform(-1, 1, 1000)
y = uniform(-1, 1, 1000)

# |x| + |y| < 1
np.mean(np.abs(x) + np.abs(y) < 1)

0.502

In [149]:
# 원점을 둘러싼 한 변이 2인 정사각형(+-1, +-1)
# 원점을 둘러싼 지름이 2(반지름이 1)인 원
# 정사각형 안의 점을 하나 뽑았을 때 마름모 안에 들어갈 확률(3.14 / 4)
x = uniform(-1, 1, 10000000)
y = uniform(-1, 1, 10000000)

np.mean(x ** 2 + y ** 2 < 1) * 4

3.1406296

# 정규분포
- 평균 m, 분산 s**2 을 모수로 하는 연속 확률 분포
- 이항 분포에서 n 이 커지면 정규 분포와 비슷해진다

- 가장 자연스러운 분포인 것은 아님, 그냥 다루기 쉽다

In [150]:
from numpy.random import normal

In [196]:
# 고객 100 명이 평균 50 만원 쓸 때(표준편차 20 만원)
하루매출 = normal(50, 20, 100)

In [197]:
# 기하분포
기간 = geometric(.05, 100)

In [198]:
기간 * 하루매출

array([ 765.62715655, 3104.90181083,  270.11045213,  301.90462983,
       2505.45047221,  212.1345803 , 2029.65958113, 2890.6093488 ,
       1017.27654571,  604.09890322,  312.70964032,  680.7951381 ,
        859.27581401,  653.53788871, 1411.17925914, 1166.49608808,
        229.7822649 , 1105.78675635, 1229.82998314, 1388.84564097,
         64.26967486,  698.98887399,  296.77389822,  419.40530418,
       1135.88423591, 2434.20032056,  991.59062268,   19.00365607,
        950.07752808,  714.24707026,  360.08111962,  813.9889548 ,
        511.65061377,   85.16101265,  363.88786583,  159.90806297,
       2849.28200273,  140.44093701, 1682.4179837 ,  506.65690131,
        673.47967635, 2320.05833395,  582.96953861,  143.54307129,
       1902.51377862, 1974.16711551,  610.93418618, 8711.74775401,
       5128.8772182 ,  441.01081402, 1112.82981227,  136.23760339,
       1609.75760677,   57.25251851,   59.12049439,  989.87768996,
        583.89652839,   65.22640545,  145.48362761, 2589.71531

In [265]:
# 0 이면 light user, 1 이면 heavy user
# 괄호 안 첫번째 값(1) 던지는 동전의 갯수
# 괄호 안 두번째 값(0.01) 은 heavy user 의 비율
유저집단 = binomial(1, .001, 100000)

In [266]:
총매출list = []
총매출 = 0

for 유저 in 유저집단:
    if 유저 == 0: # light user
        매출 = normal(1, 10)
    else: # heavy user
        매출 = normal(100, 10)
    총매출list.append(매출)
    총매출 += 매출

In [267]:
print(총매출)
총매출list

117012.02162229765


[8.38539296699096,
 4.362264401674917,
 11.911013238829991,
 11.091239266896615,
 12.049918080029766,
 9.380123229407673,
 3.156185270045506,
 -5.54592386036267,
 2.1586868158190424,
 10.683333669651326,
 -7.622115190699022,
 -8.788020400346404,
 5.161813175770674,
 2.186375842136279,
 1.310708548735477,
 -2.1251389007302572,
 15.326450135936575,
 11.467815080283462,
 -14.585684573227184,
 -15.660367190347188,
 -9.047713307949543,
 3.66128736946428,
 -7.851640471909654,
 10.537188768549637,
 11.236204898937247,
 -1.2821213447815172,
 -7.526450214301963,
 -24.575755408216008,
 -20.65539435232915,
 5.792832481820979,
 1.5975757982247116,
 -13.480386358011426,
 -5.891005247259995,
 10.878462466215764,
 2.862529860271901,
 -3.99118779313101,
 -7.488395416195141,
 20.467966279014536,
 0.38940523905592284,
 0.5594548159710809,
 15.9708151104457,
 -2.113835941034618,
 10.493185960293781,
 14.928712917221329,
 -13.996335396754654,
 -5.878807489610027,
 19.222685104856012,
 15.048294079220804,


# multinomial
- 다항분포 (주사위 던지기)
- cf. 이항분포 (동전 던지기)
- 여러가지 경우가 있다
- 각 확률이 P, 확률의 합은 1

In [214]:
from numpy.random import multinomial

In [316]:
# 괄호 안 List 는 각 면이 나올 확률
multinomial(3, [.25, .25, .25, .25])

array([0, 0, 2, 1])

In [331]:
# 100 명의 고객 중 
# 한국인 50 % 중국인 30 % 일본인 20 %
# 30일간의 결과
multinomial(100, [.5, .3, .2], 30)

array([[48, 30, 22],
       [46, 32, 22],
       [57, 26, 17],
       [48, 27, 25],
       [49, 32, 19],
       [45, 37, 18],
       [42, 40, 18],
       [47, 32, 21],
       [48, 32, 20],
       [55, 26, 19],
       [48, 32, 20],
       [49, 29, 22],
       [49, 31, 20],
       [44, 42, 14],
       [49, 37, 14],
       [49, 28, 23],
       [59, 26, 15],
       [40, 42, 18],
       [47, 39, 14],
       [51, 37, 12],
       [48, 33, 19],
       [57, 29, 14],
       [43, 35, 22],
       [53, 28, 19],
       [48, 35, 17],
       [61, 25, 14],
       [51, 30, 19],
       [47, 39, 14],
       [49, 30, 21],
       [52, 24, 24]])

# 평균으로의 회귀
- 위의 예시에서 한국인이 나올 확률 50% 확률인데, 더 큰 수도 나오고 더 작은 수도 나온다
- 더 큰 수가 나오면 그 다음날은 더 작은 수가 나온다
- 큰 수가 나오면 그 수보다 큰 수가 나오기 어렵기 때문에 그 수보다 작은 수가 나온다
- 결과적으로 오르락 내리락하는 패턴이 있는 것처럼 보인다

# 지수분포 Exponential
- 다음번 일어날 때까지 얼마나 걸리는지
- ex. 다음 버스가 올 때까지, 다음 지진이 일어날 때까지 얼마나 걸리는지
- 
- cf. poission 포아송 분포: 그 일이 일어날 때까지 얼마나 걸리는지

In [332]:
from numpy.random import exponential

In [351]:
exponential(30)

5.705361680001675

In [374]:
# 리드 타임: 고객이 도착할 때부터 서비스까지 걸리는 시간
리드타임 = 10
# 평균 30분 후에 고객 도착
# 100 명의 고객
np.mean(exponential(30, 100) < 리드타임) # 리드타임 내 추가 고객 도착 비율

# 10명까지 대기할 수 있는 경우
# 리드타임을 얼마로 해야 최적화되는가

0.25

In [356]:
# 리드타임은 같은데, 알바가 여러 명인 경우
알바 = 10
리드타임 = 10 / 알바
np.mean(exponential(30, 100) < 리드타임) # 리드타임 내 추가 고객 도착 비율

0.03